// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1cc48fb3ae3e4cfe07ea19525e74ca61b52b9b00/image-size/image-size.d.ts
declare module "image-size" {

  interface ImageInfo {
    width: number;
    height: number;
    type: string;
  }

  function sizeOf(path: string): ImageInfo;
  function sizeOf(path: string, callback: (err: Error, dimensions: ImageInfo) => void): void;

  function sizeOf(buffer: Buffer): ImageInfo;

  namespace sizeOf {}

  export = sizeOf;
}
